s1="hai ia am chetan"
print(s1.swapcase())
print(s1.count('a'))
print("+".join(s1))
print(s1.isspace())
print(s1.istitle())
print(s1.title())
print(s1.isupper())
print(s1.islower())
print(s1.isidentifier())
print(s1.isalnum())
print(s1.isalpha())
print(s1.isdigit())
#print(s1.index('book'))
print(s1.center(50))
print(s1.find('ju'))
print(s1.upper())
print(s1.capitalize())
print(s1.endswith(" book"))
print(s1.startswith("the"))